name: Desplegar en Dockerhub

on:
  push:
    tags:
      - "*.*.*-*"

jobs:
  deploy:
    name: Construir y publicar imagen
    runs-on: ubuntu-latest

    steps: 
      - name: Descargar codigo fuente
        uses: actions/checkout@v4

      - name: Iniciar sesion en dockerhub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compilar y subir imagen
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/frontend_weschler:latest
            ${{ secrets.DOCKER_USERNAME }}/frontend_weschler:${{ github.ref_name }}
          build-args: |
            VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}
            VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
            VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}
            VITE_FIREBASE_STOAGE_BUCKET=${{ secrets.VITE_FIREBASE_STOAGE_BUCKET }}
            VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
            VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }}
            VITE_FIREBASE_MEASUREMENT_ID=${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}